# Generated by Django 2.2.6 on 2021-01-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20210111_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберите c локального диска изображение для загрузки', null=True, upload_to='posts/', verbose_name='Изображение'),
        ),
    ]
